export const managerToken =
  'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVJZCI6MSwiaWF0IjoxNTE2MjM5MDIyfQ.rRjDgBGOrqDqRQS1u-wtEui-pWl-NusqhXla69PTKmA';

export const customerToken =
  'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVJZCI6MiwiaWF0IjoxNTE2MjM5MDIyfQ.aosLNCWy52lELG_LtliolyKZaM7wlzlCjvIZk-6VFrY';
